service: jobs

plugins:
  - serverless-iam-roles-per-function

custom:
  esbuild:
    bundle: true
    sourcemap: true
    minify: true
    target: 'node18'
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, "us-east-1"}
  httpApi:
    id: ${param:SharedApiGatewayId}
  vpc:
    securityGroupIds:
      - ${param:ServerlessSecurityGroupId}
    subnetIds:
      - ${param:PrivateSubnet1}
  environment:
    ENV: ${env:ENV}
    REDIS_HOST: ${param:SharedElasticCacheClusterAddress}
    REDIS_PORT: ${param:SharedElasticCacheClusterPort}
    TABLE_NAME: ${param:SharedDynamoDBTableName}
    ELASTICSEARCH_URL: 'https://${param:SharedOpensearchURL}'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'es:*'
      Resource: 'arn:aws:es:${self:provider.region}:${aws:accountId}:domain/${param:SharedOpensearchArn}/*'

functions:
  - ${file(./serverless/createIndex.yml)}
  - ${file(./serverless/createUpdateRecordIndex.yml)}
  - ${file(./serverless/search.yml)}
